module.exports = Object.freeze({
  SUCCESS: "success",
  SUCCEEDED: "succeeded",
  REFUNDED: "refunded",
  CANCELED: "canceled",
  FAIL: "fail",
  ERROR: "error",
  CANCEL: "cancel",
  REFUND: "refund",
  ACTIVE: "active",
  DEACTIVE: "deactive",
  PUBLISH: "published",
  UNPUBLISH: "unpublished",
  TRAVEL_PARTNER: "travelPartner",
  CARRY_PARCEL: "carryParcel",
  NEW: "new",
  FALSE: "false",
  TRUE: "true",
  SUSPEND: "suspend",
  STATUS_LIST: ["active", "deactive", "suspend"],
  THREAD_STATUS: ["active", "new", "closed"],
  STAFF_LIST: ["admin", "super_admin"],
  CUSTOMER_LIST: ["customer"],
  FROM_MAIL: '"Airwe" <vinay.pixerfect@gmail.com>',
  POST_STATUS_LIST: ["published", "unpublished"],
  SUPPORT_STATUS_LIST: ["new", "active", "closed"],
  ROLE_LIST: ["customer", "admin", "super_admin"],
  MODE_LIST: ["manual", "google", "facebook", "apple"],
  REVIEW_FOR_LIST: ["post", "app"],
  SERVICE_DETAIL_CATEGORY_LIST: ["travelPartner", "carryParcel"],
  SERVICE_DETAIL_TYPE_LIST: ["needy", "predicate"],
  SERVICE_DETAIL_SUB_TYPE_LIST: ["post"],
  UNDEFINED: "undefined",
  INVALID_EMAIL: "Invalid email address",
  USER: "user",
  POST: "post ",
  NULL_STRING: "",
  SUPPORT_STATUS: ["new", "active", "closed"],
  PWD_CHAR: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
  CHARACTERS: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
  DIGITS: "0123456789",
  NULL_VALUE: 0,
  MESSAGE: {
    LOGIN_SUCCESSFULLY: "Login success!",
    REGISTER_SUCCESSFULLY: "register successfully, ",
    REGISTER_SUCCESSFULLY_R: "Register successfully ",
    SENT_MAIL: "Verification code sent on your mail!",
    LOGIN_DETAIL_MAIL: "Login detail sent on mail!",
    FORGOT_MAIL: "Otp sent on your mail!",
    PASSWORD_INVALID: "Incorrect Password",
    PASSWORD_MISMATCH: "Password not matched",
    PASSWORD_CHANGE_SUCCESSFULLY: "Password change successfully!",
    EMAIL_REQUIRED: "Email address is required",
    EMAIL_INVALID: "Incorrect Email",
    NOT_ACTIVE_USER:
      "You are not active yet, please contact to administration!",
    EMAIL_VERIFIED: "Email verified successfully!",
    REQUIRED_FIELDS_MISSING: "Required fields are missing!",
    INVALID_REQ_DATA: "Invalid request data!",
    INVALID_ID: "Invalid id!",
    INVALID_TICKET: "Invalid ticket!",
    IS_REQUIRED: "is required",
    IS_INVALID: "is invalid",
    INVALID_MODE: "invalid mode",
    INVALID_DEVICE_TYPE: "Invalid device type",
    INVALID_OBJ_ID: "Invalid objectId",
    INVALID_CATEGORY: "Invalid category",
    INVALID_TYPE: "Invalid type",
    INVALID_SUB_TYPE: "Invalid sub type",
    NOT_FOUND: "not found",
    NOT_FOUND_BY_ID: "not found with ID ",
    DATA_FOUND: "Data found",
    DATA_NOT_FOUND: "Data not found",
    TICKET_NOT_FOUND: "Ticket not found",
    IS_UPDATED_SUCCESSFULLY: "is Updated Successfully!",
    FAIL_TO_UPDATED: "Error while update data!",
    ACTIVE_SUCCESSFULLY: "active successfully!",
    ADDED_SUCCESSFULLY: "added successfully!",
    CREATE_SUCCESSFULLY: "created successfully!",
    FOUND_SUCCESSFULLY: "found successfully!",
    CANCEL_SUCCESSFULLY: "cancel successfully!",
    CANCEL_SUCCESSFULLY: "cancel successfully!",
    SUCCESSFUL_PAYMENT_MAIL: "Successful payment!",
    CANCEL_PAYMENT_MAIL: "Cancel payment!",
    REFUND_PAYMENT_MAIL: "Refund payment!",
    DATA_FOUND_SUCCESSFULLY: "Data found successfully!",
    FAIL_TO_CREATE_OTP: "Fail to create OTP!",
    RESET_PASSWORD_TITLE: "Reset Password Link",
    SET_SUCCESSFULLY: "set successfully!",
    VERIFICATION_CODE_MISSING: "VerificationCode missing !",
    VERIFICATION_MAIL: "Verification mail",
    STATUS_MAIL: "Status updated mail",
    FORGOT_PASSWORD_MAIL: "Forgot password mail",
    USER_ID_MISSING: "UserId missing !",
    OTP_MISSING: "OTP missing !",
    HASH_CODE_MISSING: "HashCode missing !",
    SECRET_CODE_MISSING: "SecretCode missing !",
    OTP_INVALID: "Wrong OTP or Expired !",
    FAIL_TO_SEND_EMAIL: "Wrong OTP or Expired !",
    FAIL_TO_SEND_EMAIL: "Fail to send Email",
    EMAIL_SENT_SUCCESSFULLY: "Mail sent successfully",
    OTP_SENT_SUCCESSFULLY: "OTP sent successfully",
    STATUS_UPDATED_SUCCESSFULLY: "status updated successfully",
    PHONE_DIGIT: "should be 10 to 12 digits",
    ERROR_SEND_MAIL: "Error sending email:",
    ERROR_SENT: "Email sent:",
    ERROR_VERIFY_TRANSPORTER: "Error verifying transporter:",
    UPDATE_FOR: "Please enter what do you want to update (card or bank) ?",

    NOT_ACCESS_FOR_REVIEW: "You have not access to review for own post",
    UPDATE_FOR: "Please enter what do you want to update (card or bank) ?",
    FAIL_CREATE_CARD: "Fail to create new card",
    FAIL_REQ: "Request failed!",
    FAIL_CREATE_ACC: "Fail to create new account",

    //exist item constant
    TOKEN_GENERATE_FAIL:"Fail to generate token",
    CARD_EXIST: "Card already exists please try with another card!",
    NAME_EXIST: "Name already exists please try with another name!",
    LOCATION_EXIST: "Record already exists please try with other location!",
    EMAIL_EXIST: "Record already exists please try with other email!",
    USER_EXIST: "User already exists please try with other email!",
    TICKET_EXIST: "Ticket already exists",
    USER_NOT_FOUND: "User not found",
    POST_NOT_FOUND: "Post not found",
    USER_NOT_EXIST_WITH_EMAIL: "User not exists with this email!",
    USER_SIGNUP_SUCCESSFULLY: "USER SIGNUP SUCCESSFULLY!",
    FORGOT_PASSWORD_SUCCESSFULLY: "FORGOT PASSWORD MAIL SEND SUCCESSFULLY!",
    UPDATED_SUCCESSFULLY: "updated successfully!",
    DELETED_SUCCESSFULLY: "deleted successfully!",
    FAIL_TO_SUBMIT: "Failed to submit data",
    SOMETHING_WRONG: "Something went wrong",
    NO_DATA: "No data found",
    TOKEN_NOT_GENERATED: "Token not generated",
    TOKEN_GENERATED: "Token generated successfully!",
    INVALID_EMAIL: "Email is invalid",
    INVALID_ROLE: "Role is invalid",
    INVALID_REVIEW_FOR: "Review for is invalid",
    INVALID_OBJ_ID: "Invalid ObjectId",
    NOT_ACCESS: "You have no access ",
    USER_LOGIN_GOOGLE: "Login with google successfully",
    USER_LOGIN: "Login successfully",
    AUTHENTICATION_TOKEN_FAIL: "Authentication token fail",
    NO_TOKEN_PROVIDED: "no token provided",
    TOKEN_EXPIRED: "Token expired!",
    PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully",
    PASSWORDS_DO_NOT_MATCH: "Passwords do not match",
    ERROR_OCCURRED: "Some error occurred while retrieving data",
    RATE_ERROR: "Rate must be a number between 0 to 5",
    FILE_UPLOAD_ERROR: "File not uploaded",
    USER_ID_NOT_FOUND: "User id not found",
    ATTACHMENT_OR_MESSAGE: "Attachment or message ",
    INVALID_REASON:
      "Please enter valid reason eg.Fraudulent or Requested by customer or Abandoned !.",
    PAYMENT_ALREADY_DONE: "Payment already done successfully!!.",
  },
  COLLECTION: {
    USER: "User ",
    POST: "Post ",
    FEEDBACK: "Feedback and review ",
    SUPPORT: "Support request ",
    PAYMENT_HISTORY: "Payment history ",
    REFUND: "Refund ",
    THREAD: "Thread ",
    ACCOUNT: "Account ",
    TRANSFER: "Transfer ",
    TRANSFER_REQ: "Transfer request ",
  },
  COMMON: {
    SUPER_ADMIN: "super_admin",
    ADMIN: "admin",
    USER: "user",
    CUSTOMER: "customer",
    NAME: "Name ",
    EMAIL: "Email ",
    PHONE_NO: "Phone number ",
    PASSWORD: "Password ",
    OTP: "Otp ",
    SECRET_CODE: "Secret code ",
    NEW_PASSWORD: "New password ",
    CONFIRM_PASSWORD: "Confirm password ",
    DEVICE_TOKEN: "Device token ",
    DEVICE_TYPE: "Device type ",
    ROLE: "Role ",
    MODE: "Mode ",
    STATUS: "Status",
    MANUAL: "manual",
    GOOGLE: "google",
    FACEBOOK: "facebook",
    APPLE: "apple",
    ANDROID: "android",
    IOS: "ios",
    TYPE: "Type",
    DESC: "desc",
    ASC: "asc",
    UPDATED_AT: "updatedAt",
    CREATED_AT: "createdAt",
    CUSTOMER: "customer",
    CLOSED: "closed",
    URL: "url",
    FILE_NAME: "filename",
    REVIEW: "Review ",
    APP: "app",

    CARD_DATA: "Card data ",
    DATA: "Data ",
    REASON: "Reason ",
    ID: "id ",
    OR: "or ",
    FINISH: "finish",
    URL: "url",
    FILE_NAME: "filename",
    REVIEW: "Review ",
    AMOUNT: "amount ",
  },
  FIELD: {
    CARD_SML: "card",
    BANK_SML: "bank",
    NAME: "name",
    FROM: "From ",
    TO: "To ",
    DATE_TYPE: "Date type ",
    TYPE: "Type ",
    SUB_TYPE: "Sub type ",
    CATEGORY: "Category ",
    TITLE: "Title ",
    MONTH: "Month ",
    TRAVEL_DATE: "Travel date ",
    MEET_LOCATION: "Meet location ",
    MORE_DETAIL: "More detail ",
    NOTES: "Notes ",
    ASSISTANT_CONTAIN: "Assistant contain ",
    PARCEL_CONTAIN: "Parcel contain ",
    WEIGHT: "Weight ",
    CARRY_PARCEL: "carryParcel",
    TRAVEL_PARTNER: "travelPartner",
    ATTACHMENT: "attachment",
    RATE: "Rate ",
    TITLE: "Title ",
    DESCRIPTION: "Description ",
    CUSTOMER: "Customer ",
    POST: "Post ",
    CARD: "Card ",
    BANK: "Bank ",
    AMOUNT: "Amount ",
    CARD_TOKEN: "Card token ",
    PAYMENT_TYPE: "Payment type ",
    PAYMENT_METHOD: "Payment method ",
    ADDRESS_LINE_ONE: "Address line one ",
    ADDRESS_LINE_TWO: "Address line two ",
    ZIP_CODE: "Postal code ",
    POSTAL_CODE: "Zip code ",
    CITY: "City ",
    STATE: "State ",
    COUNTRY: "Country ",
    CURRENCY: "Currency ",
    EXP_MONTH: "Expiry month ",
    EXP_YEAR: "Expiry year ",
    ACCOUNT_HOLDER_NAME: "Account holder name ",
    ACCOUNT_HOLDER_TYPE: "Account holder type ",
    ACCOUNT_TYPE: "Account type ",
    ACCOUNT_NUMBER: "Account number ",
    ROUTING_NUMBER: "Routing number ",
    PAYMENT: "Payment ",
  },
  API: {
    OAUTH_TOKEN: "/oauth/token",
  },
  RESET_UI_URL: "/reset-password",
  USER_PHOTO: "userPhoto",
  PAYMENT_CONSTANT: {
    REASON_LIST: [
      { key: "duplicate", value: "Duplicate" },
      { key: "fraudulent", value: "Fraudulent" },
      { key: "requested_by_customer", value: "Requested by customer" },
      { key: "abandoned", value: "Abandoned" },
      { key: "failed_invoice", value: "Failed Invoice" },
    ],
    STATUS_LIST: {
      REQUIRES_ACTION: "requires_action",
      SUCCEEDED: "succeeded",
    },
    MESSAGE: {
      PAYMENT_SUCCESS: "Payment succeeded!",
      PAYMENT_FAIL: "Payment failed!",
      CARD_CREATE_FAIL: "Fail to create card!",
    },
    PAYMENT_TYPE_LIST: ["card", "bank_account"],
    CANCELLATION_REASON_LIST: [
      "duplicate",
      "fraudulent",
      "requested_by_customer",
      "abandoned",
      "failed_invoice",
      "void_invoice",
      "automatic",
    ],
    REQUIRED_FIELD:
      "The request was unacceptable, often due to missing a required parameter",
    NOT_FOUND: "The requested resource doesn't exist.",
    STRUCTURE_LIST: ["government_instrumentality",
      "governmental_unit",
      "incorporated_non_profit",
      "limited_liability_partnership",
      "multi_member_llc",
      "private_company",
      "private_corporation",
      "private_partnership",
      "public_company",
      "public_corporation",
      "public_partnership",
      "single_member_llc",
      "sole_proprietorship",
      "tax_exempt_government_instrumentality",
      "unincorporated_association",
      "unincorporated_non_profit",
      "free_zone_llc",
      "sole_establishment",
      "free_zone_establishment",
      "llc"],
  },

  UPLOAD_DOC_PATH: {
    SUPPORT_DOC_PATH: "../document/support_document",
  },

  
});
